version: '3.8'

services:
  offboarding:
    build: .
    image: cladtek/offboarding:latest
    container_name: offboarding_app
    ports:
      - "80:8000"
    environment:
      - ALGORITHM=HS256
      - EMAIL_SENDER=diogo.xavier@cladtek.com
      - PORT=587
      - EMAIL_RECEIVER=diogo.xavier@cladtek.com
      - SMTP_SERVER="smtp.gmail.com"
    secrets:
      - DATABASE_URL
      - SECRET_KEY
      - INTOUCH_TOKEN
      - INTOUCH_URL
      - EMAIL_PASSWORD
      - AD_USERNAME
      - AD_PASSWORD
      - AD_SERVER
      - AD_DOMAIN
      - AD_BASE_DN
      - DISABLED_OU
      - TURNSTILE_A_URL
      - TURNSTILE_B_URL
      - TURNSTILE_A_SESSION
      - TURNSTILE_B_SESSION
    volumes:
      - offboarding_data:/app/data
    restart: always

secrets:
  DATABASE_URL:
    external: true
  SECRET_KEY:
    external: true
  INTOUCH_TOKEN:
    external: true
  iINTOUCH_URL:
    external: true
  EMAIL_PASSWORD:
    external: true
  AD_USERNAME:
    external: true
  AD_PASSWORD:
    external: true
  AD_SERVER:
    external: true
  AD_DOMAIN:
    external: true
  AD_BASE_DN:
    external: true
  DISABLED_OU:
    external: true
  TURNSTILE_A_URL:
    external: true
  TURNSTILE_B_URL:
    external: true
  TURNSTILE_A_SESSION:
    external: true
  TURNSTILE_B_SESSION:
    external: true

volumes:
  offboarding_data: