"""create offboarding tables

Revision ID: 4d54e330fdd0
Revises: 67cf1a2f571e
Create Date: 2026-02-20 14:36:33.209409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.user_model import SqliteUUID

# revision identifiers, used by Alembic.
revision: str = '4d54e330fdd0'
down_revision: Union[str, Sequence[str], None] = '67cf1a2f571e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offboarding_records',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('offboarded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('performed_by_username', sa.String(length=100), nullable=False),
    sa.Column('user_id', SqliteUUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offboarding_records_offboarded_at'), 'offboarding_records', ['offboarded_at'], unique=False)
    op.create_index(op.f('ix_offboarding_records_registration'), 'offboarding_records', ['registration'], unique=False)
    op.create_index(op.f('ix_offboarding_records_user_id'), 'offboarding_records', ['user_id'], unique=False)
    op.create_table('revoked_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offboarding_id', SqliteUUID(), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offboarding_id'], ['offboarding_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_accesses_offboarding_id'), 'revoked_accesses', ['offboarding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_accesses_offboarding_id'), table_name='revoked_accesses')
    op.drop_table('revoked_accesses')
    op.drop_index(op.f('ix_offboarding_records_user_id'), table_name='offboarding_records')
    op.drop_index(op.f('ix_offboarding_records_registration'), table_name='offboarding_records')
    op.drop_index(op.f('ix_offboarding_records_offboarded_at'), table_name='offboarding_records')
    op.drop_table('offboarding_records')
    # ### end Alembic commands ###
