"""change audit_log user_id to uuid

Revision ID: 67cf1a2f571e
Revises: 894a742b9547
Create Date: 2026-01-07 12:44:27.727919

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app.models

# revision identifiers, used by Alembic.
revision: str = '67cf1a2f571e'
down_revision: Union[str, Sequence[str], None] = '894a742b9547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'audit_logs',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False)
    )
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=app.models.user_model.SqliteUUID(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=app.models.user_model.SqliteUUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###
