"""create_tables

Revision ID: fb3de63d89e3
Revises:
Create Date: 2026-05-26 14:04:09.334855

"""
from typing import Sequence, Union

from app.modules.shared import SqliteUUID
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb3de63d89e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('user_id', SqliteUUID(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('target_user_id', SqliteUUID(), nullable=True),
    sa.Column('target_username', sa.String(), nullable=True),
    sa.Column('target_registration', sa.String(), nullable=True),
    sa.Column('resource', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('userRole', sa.Integer(), server_default='3', nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', SqliteUUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offboarding_records',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=False),
    sa.Column('offboarded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('performed_by_username', sa.String(length=100), nullable=False),
    sa.Column('user_id', SqliteUUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offboarding_records_offboarded_at'), 'offboarding_records', ['offboarded_at'], unique=False)
    op.create_index(op.f('ix_offboarding_records_registration'), 'offboarding_records', ['registration'], unique=False)
    op.create_index(op.f('ix_offboarding_records_user_id'), 'offboarding_records', ['user_id'], unique=False)
    op.create_table('onboarding_checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sa.String(length=150), nullable=False),
    sa.Column('employee_registration', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', SqliteUUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_checklists_employee_registration'), 'onboarding_checklists', ['employee_registration'], unique=False)
    op.create_table('onboarding_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['onboarding_checklists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_fields_checklist_id'), 'onboarding_fields', ['checklist_id'], unique=False)
    op.create_table('onboarding_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', SqliteUUID(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['onboarding_checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_items_checklist_id'), 'onboarding_items', ['checklist_id'], unique=False)
    op.create_table('revoked_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offboarding_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offboarding_id'], ['offboarding_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_accesses_offboarding_id'), 'revoked_accesses', ['offboarding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_accesses_offboarding_id'), table_name='revoked_accesses')
    op.drop_table('revoked_accesses')
    op.drop_index(op.f('ix_onboarding_items_checklist_id'), table_name='onboarding_items')
    op.drop_table('onboarding_items')
    op.drop_index(op.f('ix_onboarding_fields_checklist_id'), table_name='onboarding_fields')
    op.drop_table('onboarding_fields')
    op.drop_index(op.f('ix_onboarding_checklists_employee_registration'), table_name='onboarding_checklists')
    op.drop_table('onboarding_checklists')
    op.drop_index(op.f('ix_offboarding_records_user_id'), table_name='offboarding_records')
    op.drop_index(op.f('ix_offboarding_records_registration'), table_name='offboarding_records')
    op.drop_index(op.f('ix_offboarding_records_offboarded_at'), table_name='offboarding_records')
    op.drop_table('offboarding_records')
    op.drop_table('users')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
