"""Added targets column in audit_logs table. Fixed UUID error in RevokedAccess table

Revision ID: fc3586699091
Revises: 4d54e330fdd0
Create Date: 2026-02-23 11:57:33.780562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector
from app.models.user_model import SqliteUUID


# revision identifiers, used by Alembic.
revision: str = 'fc3586699091'
down_revision: Union[str, Sequence[str], None] = '4d54e330fdd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('target_user_id', SqliteUUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('target_username', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('target_registration', sa.String(), nullable=True))
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # 2. Pega as colunas que já existem na tabela audit_logs
    existing_columns = [c['name'] for c in inspector.get_columns('audit_logs')]

    # 3. Só adiciona as colunas SE elas ainda não existirem
    if 'target_user_id' not in existing_columns:
        op.add_column('audit_logs', sa.Column('target_user_id', SqliteUUID(), nullable=True))
    
    if 'target_username' not in existing_columns:
        op.add_column('audit_logs', sa.Column('target_username', sa.String(), nullable=True))
        
    if 'target_registration' not in existing_columns:
        op.add_column('audit_logs', sa.Column('target_registration', sa.String(), nullable=True))

    # 4. Continua com a correção da tabela revoked_accesses (isso vai rodar normalmente)
    with op.batch_alter_table('revoked_accesses', schema=None) as batch_op:
        batch_op.alter_column(
            'offboarding_id',
            type_=sa.Integer(),
            existing_type=sa.BLOB(), # ou SqliteUUID() dependendo do estado anterior
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_accesses', schema=None) as batch_op:
        batch_op.alter_column(
            'offboarding_id',
            type_=SqliteUUID(),
            existing_type=sa.Integer(),
            nullable=False
        )
    op.drop_column('audit_logs', 'target_registration')
    op.drop_column('audit_logs', 'target_username')
    op.drop_column('audit_logs', 'target_user_id')
    # ### end Alembic commands ###
