from enum import Enum


class AuditAction(str, Enum):
    SYSTEM_LOGIN = "SYSTEM_LOGIN"
    SYSTEM_LOGOUT = "SYSTEM_LOGOUT"
    TOKEN_REFRESH = "TOKEN_REFRESH"

    LIST_USERS = "LIST_USERS"
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"
    READ_CURRENT_USER = "READ_CURRENT_USER"

    SEARCH_AD_USER = "SEARCH_AD_USER"
    DISABLE_AD_USER = "DISABLE_AD_USER"

    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
    EXPORT_AUDIT_LOGS = "EXPORT_AUDIT_LOGS"

    SYSTEM_START = "SYSTEM_START"
    SYSTEM_STOP = "SYSTEM_STOP"
    SYSTEM_ERROR = "SYSTEM_ERROR"
